export const AI_KB: [string[], string][] = [
  [['sleep', 'sleeping', 'nap', 'tired'], 'Sleep is crucial at this age! Newborns need 14–17h, and 3–6 month olds need 12–16h total. A consistent routine helps: bath → feeding → gentle rocking → dark, quiet room. White noise can work wonders for some babies. If your baby is waking every 1–2h at night past 3 months, try a slightly earlier bedtime — overtiredness makes it harder to sleep through.'],
  [['feed', 'feeding', 'hungry', 'milk', 'breast', 'bottle', 'formula', 'solid'], 'Feeding is the cornerstone! Newborns typically feed every 2–3h (8–12×/day). By 3–4 months this often settles to every 3–4h. Watch for hunger cues: rooting, sucking fists, or turning their head side-to-side. Cluster feeding in the evenings is totally normal and doesn\'t mean you have insufficient milk.'],
  [['cry', 'crying', 'fussy', 'fussing', 'colic', 'witching'], 'Crying is their main language right now. The most common causes are hunger, tiredness, gas, overstimulation, or needing comfort. Try the \'5 Ss\': Swaddle, Side/stomach position, Shush, Swing, and Suck. If crying is inconsolable for more than 3 hours/day, 3+ days a week, mention it at the next checkup — it could be colic, which peaks around 6 weeks and usually resolves by 3–4 months.'],
  [['weight', 'grow', 'growth', 'gain', 'heavy', 'light', 'size'], 'Weight gain in the first year is rapid! Babies typically double their birth weight by 5 months and triple it by 12 months. In the first few months, expect roughly 150–200g gain per week. What matters most is consistent growth along a percentile curve — not hitting a specific number. Your pediatrician will plot this at every checkup.'],
  [['vaccine', 'vaccination', 'shot', 'immuniz', 'jab'], 'Vaccinations protect against serious diseases and are given at birth, 2, 4, 6, 12, and 15–18 months (among others). Mild fussiness, a sore leg, or low-grade fever (under 38.5°C) after shots is normal and usually resolves within 24–48h. You can give age-appropriate acetaminophen for comfort. Contact your doctor if fever exceeds 39°C or baby seems very unwell.'],
  [['solid', 'food', 'eat', 'cereal', 'puree', 'spoon'], 'Most babies are ready for solids around 4–6 months. Signs of readiness: can sit with minimal support, good head control, shows interest in food, and the tongue-thrust reflex has faded. Start with single-ingredient purees (sweet potato, avocado, banana, peas). Introduce one new food every 3–4 days so you can spot any allergies. Breast milk or formula remains the primary nutrition source until 12 months.'],
  [['diaper', 'poop', 'stool', 'wet', 'constipat', 'diarrhea'], 'Diaper patterns vary widely by baby and feeding method. Breastfed newborns may have 8–12 wet diapers and 3–4 dirty ones per day. By 6 weeks, some breastfed babies go several days between poops — this is often normal as long as the stool is still soft when it comes. Fewer than 6 wet diapers per day could signal dehydration; call your doctor right away.'],
  [['develop', 'milestone', 'crawl', 'walk', 'talk', 'word', 'roll', 'sit', 'stand'], 'Every baby develops at their own pace! Typical milestones: social smile (6–8 wks), cooing (2–3 mo), rolling (4–6 mo), sitting with support (4–5 mo), unassisted sitting (6–8 mo), crawling (7–10 mo), first words (9–12 mo), walking (9–15 mo). A range is always normal. If you\'re worried about a skill not appearing, bring it up at the next checkup — early intervention is always better than waiting.'],
];

export function getAIReply(input: string, babyName: string): string {
  const lower = input.toLowerCase();
  for (const [keywords, response] of AI_KB) {
    if (keywords.some((k) => lower.includes(k))) {
      return response;
    }
  }
  return `That's a great question about ${babyName}! Every baby is unique, and the best person to give specific advice is your pediatrician who knows ${babyName}'s full history. In general, trust your instincts as a parent — you know your baby best. Keep tracking consistently in Bebio and I can help you spot patterns. What else would you like to know?`;
}
